config/routes.rb
VisotaParaclubRu::Application.routes.draw do

  resources :voices, :only => [:create, :destroy]	
  resources :votes
  resources :events

  post "events/upload_photos"
  match '/events/:id/upload_photos', :to => 'events#upload_photos' #загрузка с помощью dropzone.js и собственную функцию
	get "admin_tools/deleted_albums"   #удалённые альбомы
	get "admin_tools/deleted_themes"   #удалённые темы
	get "admin_tools/deleted_messages" #удалённые сообщения или комментарии
	get "admin_tools/deleted_articles" #удалённые статьи
	get "admin_tools/deleted_photos"   #удалённые статьи
	get "admin_tools/hidden_albums"    #скрытые альбомы
	get "admin_tools/hidden_themes"	   #скрытые альбомы
	get "admin_tools/hidden_messages"  #скрытые сообщения
	get "admin_tools/hidden_articles"  #скрытые статьи
	get "admin_tools/hidden_photos"    #скрытые фотографии
	get "admin_tools/deleted_entities" #удалённые объекты
  get "admin_tools/hidden_entities"  #скрытые объекты	
	get "admin_tools/site_images" #изображения для сайта	
	get "admin_tools/entities_recovery"	#Восстановление удалённых объектов
	get "admin_tools/disabled_events" #Скрытые новости
	get "admin_tools/adaptation_to_new"     #Создать темы
  
  resources :articles
  get "articles/bind_videos_and_albums"
  post "articles/upload_photos"
  match '/articles/:id/upload_photos', :to => 'articles#upload_photos'
  match '/articles/:id/bind_videos_and_albums', :to => 'articles#bind_videos_and_albums'

  resources :old_messages, :only => [:index, :edit, :update, :destroy]
  get "old_messages/get_old_messages"
  get "old_messages/old_msg_users"
  get "old_messages/assign_users_to_old_msgs"
  post "old_messages/assign_users_to_old_msgs"
  
  resources :messages
  get "messages/replace_message"
  get "messages/do_replace_message"
  post "messages/upload_photos"
  match '/messages/:id/replace_message', :to => 'messages#replace_message'
  match '/messages/:id/upload_photos', :to => 'messages#upload_photos' #загрузка с помощью dropzone.js и собственную функцию photosUploader() в application.js
  match '/do_replace_message', :to => 'messages#do_replace_message'
  
  resources :themes
  get "themes/merge_themes"
  get "themes/get_themes_list"
  post "themes/do_merge_themes"
  post "themes/theme_switcher"
  post "themes/add_photos"
  post "themes/add_files"
  post "themes/upload_photos"
  match '/themes/:id/theme_switcher', :to => 'themes#theme_switcher'
  match '/get_themes_list', :to => 'themes#get_themes_list'
  match '/themes/:id/merge_themes', :to => 'themes#merge_themes'
  match '/themes/:id/new_message', :to => 'themes#new_message' #Новое сообщение в теме
  match '/themes/:id/add_photos', :to => 'themes#add_photos' #Загрузка фото
  match '/themes/:id/add_files', :to => 'themes#add_files' #Загрузка файлов
  match '/do_merge_themes', :to => 'themes#do_merge_themes'
  match '/themes/:id/upload_photos', :to => 'themes#upload_photos' #загрузка с помощью dropzone.js и собственную функцию photosUploader() в application.js

  resources :topics
  match '/visota_life', :to => 'topics#index'
  match '/gost.htm', :to => 'topics#index'

  resources :videos
  get "videos/new_comment"
  match '/videos/:id/new_comment', :to => 'videos#new_comment'

  resources :photos
  get "photos/edit_photos"
  get "photos/recovery"
  post "photos/edit_photos"
  post "photos/update_photos"
  match '/photos/:id/recovery', :to => 'photos#recovery' #восстановление
  match '/edit_photos', :to => 'photos#edit_photos'
  match '/update_photos', :to => 'photos#update_photos'

  resources :photo_albums
  get "photo_albums/unbinded_to_article_albums"
  post "photo_albums/upload_photos"
  get "photo_albums/get_albums_list"
  match '/get_albums_list', :to => 'photo_albums#get_albums_list'
  match '/unbinded_to_article_albums', :to => 'photo_albums#unbinded_to_article_albums'#Ссылка на вывод списка альбомов не прикрепленных к статье...
  match '/photo_albums/:id/upload_photos', :to => 'photo_albums#upload_photos' #загрузка с помощью dropzone.js и собственную функцию photosUploader() в application.js

  resources :steps
  
  resources :users
  get "users/password_mail_sent"
  get "users/make_mail"
  get "users/remember_password"
  get "users/mail_switcher"
  get "users/thanks"
  put "users/update_mailer"
  get "users/user_check"
  get "users/mail_test"
  get "users/check_email_and_name"
  get "users/videos"
  get "users/photo_albums"
  get "users/articles"
  get "users/steps"
  match '/password_mail_sent', :to => 'users#password_mail_sent'
  match '/make_mail', :to => 'users#make_mail'
  match '/remember_password', :to => 'users#remember_password'
  match '/thanks', :to => 'users#thanks'
  match '/mail_switcher', :to => 'users#mail_switcher'
  match '/user_check', :to => 'users#user_check'
  match "/pilots", :to => 'users#index'
  match "/welcome", :to => 'users#welcome'
  match "/update_mailer", :to => 'users#update_mailer'
  match "/check_email_and_name", :to => 'users#check_email_and_name' #проверка имени и почтового адреса на занятость.
  match "/users/:id/videos", :to => "users#videos"
  match "/users/:id/steps", :to => "users#steps"
  match '/users/:id/photo_albums', :to => 'users#photo_albums'
  match '/users/:id/articles', :to => 'users#articles'
  
  resources :sessions, :only => [:new, :create, :destroy]
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  match '/create_session',  :to => 'sessions#create'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  get "pages/index"
  get "pages/school"
  get "pages/contacts"
  get "pages/about_us"
  get "pages/feed"
  get "pages/search"
  match '/index', :to => 'pages#index'
  match '/school', :to => 'pages#school'
  match '/about_us', :to => 'pages#about_us'
  match '/contacts', :to => 'pages#contacts'
  match '/styles', :to => 'pages#styles'
  match '/feed', :to => 'pages#feed'
  match '/search', :to => 'pages#search'
  

  root :to => 'pages#index'

end

app/helpers/messages_helper.rb
module MessagesHelper
	def my_message_errors
		@content_error = "" 
		@content_f_class = "norm"
		if @formMessage.errors[:content] != [] and @formMessage.errors[:content] != nil
			@content_f_color = "err"
			@formMessage.errors[:content].each do |err|
				@content_error += "#{err}<br />"
			end
		end
	end
	def message_theme_box(message, show_buttons, i) 
		p = {
				:tContent => message_body(message, show_buttons), 
				:fContent => answrToMsg(message), 
				:classLvl_1 => 'msgs', 
				:idLvl_1 => "m_#{message.id}", 
				:classLvl_2 => 'msgBody', 
				#:idLvl_2 => '', 
				:classBg => 'cWrapper', 
				:parity => i
			}
		return c_box_block(p)
	end
	def answrToMsg(m)
		return "<div class = 'answr' id = 'answr_to_#{m.id}' style='display: none;'></div>" if user_type != 'guest' and user_type != 'bunned'
	end 
	def author_string(m)
		t = ''
		if m.theme != nil
			t = 'Автор темы' if m.user == m.theme.user
		end
		if m.video != nil
			t = 'Автор видео' if m.user == m.video.user
		end
		if m.photo != nil
			t = 'Автор фото' if m.user == m.photo.user
		end
		if m.photo_album != nil
			t = 'Автор альбома' if m.user == m.photo_album.user
		end
		t = "<p class = 'istring_m medium-opacity'>#{t}</p>" if t != ''
		return t
			#{'' if message.user == message.theme.user}
	end
	def message_body(message, show_buttons)
		tread = message.get_visible_tread
		html = "
				<a name = 'msg_#{message.id}'></a>
				<table>
					<tr>
						<td valign = 'middle' align = 'left'  colspan = '2' style='height: 45px;'>
							<p class = 'istring_m norm medium-opacity'>Написано #{message.created_at.to_s(:ru_datetime)} #{answer_to_msg(message)}</p>
						</td>
					</tr>
					<tbody id = 'middle'>
						<td id = 'usr'>
							#{message_user_row(message)}
							<br />
								#{author_string(message)}
							#{("<br />#{link_to 'Редактировать фото', "/edit_photos?e=msg&e_id=#{message.id}", :class => 'b_link'}") if message.user == current_user and message.photos != []}
						</td>
						<td>
							<div class = 'central_field' style = 'width: 95%;'>
								#{message_photo(message)}
								<span align = 'left' id = 'content' class = 'mText'>#{message.content_html}</span>
								
								<br />
								#{message.message_updater}
								#{"<br /><div class = 'central_field' style = 'width: 760px;'>#{message_list_photos(message)}</div>" if message.visible_photos != []}
								#{"<br />#{list_attachments(message.attachment_files)}" if message.attachment_files != []}
							</div>
						</td>
					</tbody>
					<tr>
						<td colspan = '2' valign = 'middle'>
							<table style = 'width: 100%; height: 100%;'>
								<tr>
									<td align = 'left' valign = 'middle' style = 'width: 60%;'>
										#{control_buttons(msg_block_buttons_bottom_in_theme(message, tread.count)) if show_buttons == true and @theme != nil}
										#{control_buttons(msg_block_buttons_bottom_in_video(message, tread.count)) if show_buttons == true and @video != nil}
										#{control_buttons(msg_block_buttons_bottom_in_album(message, tread.count)) if show_buttons == true and @album != nil}
									</td>
									<td align = 'right' valign = 'middle'>
										<span  class = 'istring_m norm medium-opacity'>Ответов: #{tread.count}</span>
									</td>
								</tr> 
							</table>
						</td>
					</tr>			
				</table>		
		"
		return html
	end
	def gsub_test(text)
	   text.gsub(/\[fNum\](\n|\r)+((\d+\.\s.*(\n|\r)+)+)\[\/fNum\]/) do #\n((\d+\.\s.*\n)*)(\n)*\ \n\d+\.\s.*\n\[\/fNum\]
		c = $2
		if c != '' and c != nil 
			c = c.gsub(/(\d+)\.\s(.*)(\n|\r)/){"<li type = '1' value = #{$1}>#{$2}</li>"}
			"<ul class = 'cnt-un-num'>#{c}</ul>"
		else
			''
		end
		%{<ul class = 'cnt-un-num'>#{c}</ul>}
	  end
	end
	
	def message_photo(message)
		if message.photo != nil
			return "<div class = 'central_field' style = 'width:500px;'><p class='istring_m medium-opacity'>Комментарий к фотографии</p>#{image_tag message.photo.link, :width => '500px' if message.photo.isHorizontal?}#{image_tag message.photo.link, :height => '250px' if !message.photo.isHorizontal?}</div><br />" if message.photo != @photo 
		end
		return ''
	end
	def message_user_row(message)
		if message.user_id == nil or message.user_id == 0 and message.user_name != nil and message.user_name != ''
			return "<span class = 'istring_m norm'>#{message.user_name}</span><br />#{image_tag('/files/undefined.png', :width => '90px')}"
		elsif message.user_id != nil and message.user_id != 0
			return "#{link_to message.user.name, message.user, :class => 'b_link_i'}<br />#{image_tag(message.user.alter_avatar, :width => '90px')}"
		elsif message.user_name == nil and message.user_name == '' and message.user_id == nil or message.user_id == 0 	
			return "<span class = 'istring_m norm'>Гость</span><br />#{image_tag('/files/undefined.png', :width => '90px')}"
		end
	end
	#new_message_init
	def newMessageFormInitial(display, formClass)
		form = ''
		flag = false
		type = 'comment'
		if (@theme != nil || @photo != nil || @album != nil || @video != nil) && (user_type != 'bunned' and user_type != 'guest')
			@tmpMessage = current_user.message_draft
			if @theme != nil
				if userCanCreateMsgInTheme?(@theme)
					@alterReturnTo = theme_path(@theme)
					flag = true
					type = 'message' if @photo == nil
					type = 'comment' if @photo != nil
					if @tmpMessage.theme_id != @theme.id and @tmpMessage.topic_id != @theme.topic_id
						@tmpMessage.clean
						@tmpMessage.update_attributes(:theme_id => @theme.id, :topic_id => @topic_id)
					end
				end
			end
			if @video != nil 
				if !is_not_authorized?
					@alterReturnTo = video_path(@video)
					flag = true
					if @tmpMessage.video_id != @video.id
						@tmpMessage.clean
						@tmpMessage.update_attribute(:video_id, @video.id)
					end
				end
			end
			if @album != nil 
				if !is_not_authorized?
					flag = true
					chAlbumFlag = false
					chPhotoFlag = false
					@alterReturnTo = photo_album_path(@album)
					if @photo != nil
						@alterReturnTo = photo_path(@photo)
						chPhotoFlag = true if @tmpMessage.photo_id != @photo.id
					end
					chAlbumFlag = true if @tmpMessage.photo_album_id != @album.id
					if chAlbumFlag || chPhotoFlag
						@tmpMessage.clean
						if chAlbumFlag and chPhotoFlag
							@tmpMessage.update_attributes(:photo_id => @photo.id, :photo_album_id => @photo.photo_album_id)
						elsif chAlbumFlag and !chPhotoFlag
							@tmpMessage.update_attribute(:photo_album_id, @album.id)
						end	
					end
				end
			end
			if @message_to != nil
				flag = true
			end
		end
		flag &= userCanCreateMsg?
		if flag == true
			ent = @tmpMessage
			if @formMessage == nil
				@formMessage = Message.new
			else
				ent = @formMessage
			end
			@add_functions = (@add_functions == nil)? "initMessageForm(#{ent.id.to_s}, '#{formClass}', '#{type}');":@add_functions+"initMessageForm(#{ent.id.to_s}, '#{formClass}', '#{type}');"
			form = "<div style = 'display: #{display};' id = 'newMsgForm'>#{buildMsgForm(type)}</div>"
			p = {:tContent => form}
			return c_box_block(p)
		else
			return ''
		end
	end
	def buildMsgForm(type)
		#отрисовывается с помощью js функции initMessageForm(msg_id)
		form_for(@formMessage, :multipart => 'true') do |f|
		"
			<div class = 'mForm'>
				
				<div style = 'display: none;'>#{ f.file_field :uploaded_photos, :multiple => 'true' if type != 'comment'}</div>
				#{ hidden_field :info, :return_to_link, :value => getMsgPathLinkAfterSave}
				#{ f.hidden_field :message_id, :value => @message_to.id if @message_to != nil }
				#{ f.hidden_field :theme_id, :value => @theme.id if @theme != nil}
				#{ f.hidden_field :photo_id, :value => @photo.id if @photo != nil}
				#{ f.hidden_field :video_id, :value => @video.id if @video != nil}
				#{ f.hidden_field :photo_album_id, :value => @album.id if @album != nil}
				<div class = 'central_field' style = 'width: 950px;'>
					<br />
					<table id = 'msg_table' style = 'width: 100%;'>
						<tr>
							<td id = 'frm' valign = 'top'>
									<table id = 'formMenuTable'>
										<tr>
											<td id = 'formButtons'>
											</td>
										</tr>
										<tr>
											<td id = 'formMenus'>
											</td>
										</tr>
									</table>
									#{ f.label :content, 'Текст сообщения' if type == 'message'}#{ f.label :content, 'Комментарий' if type == 'comment'}<br />
									#{ f.text_area :content, :cols => 90, :rows => '7', :defaultRows => '7', :class=> 't_area'}
									<div><p class = 'istring #{@content_f_color if @content_f_color != nil}' id = 'cLength'><span id = 'txtL'></span> <span id = 'txtErr'>#{@content_error if @content_error != nil}</span><span id = 'txtErrSrv'>#{@content_error if @content_error != nil}</span></p></div>
								<div class='actions'>
									#{ f.submit 'Отправить', :class=>'butt' }
								</div>
								<div id = 'editorPreview' class = 'mText' style = 'position: relative; width: 100%; margin-top: 20px; margin-bottom: 20px; '>
								
								</div>
							</td>
							#{"
							<tr>

							<td id = 'formPhotos'>
								#{f.label :uploaded_photos, 'Фотографии сообщения'}<br />
								<div class = 'dropzone' id = 'ph_to_frm'>
								</div>
								<div id = 'uploadedPhotos'>
								</div>
								<div><p class = 'istring #{@photos_f_color if @photos_f_color != nil}' id = 'iLength'><span id = 'txtL'></span> <span id = 'txtErr'>#{@photos_error if @photos_error != nil}</span><span id = 'txtErrSrv'>#{@photos_error if @photos_error != nil}</span></p></div>
							</td>
							</tr>
							" if type != 'comment'}
						</tr>
					</table>
					<br />
				</div>
			</div>
			".html_safe
		end
	end
	def getMsgPathLinkAfterSave
		if @return_to == nil or @return_to == ''
			return @alterReturnTo
		else 
			return @return_to
		end
		
	end
#new_message_init end
	def answer_to_msg(message)		
		if message.message == nil
			return ""
		else
			if message.message.user != current_user
				answer_to = message.message.user.name
				if message.theme != nil

app/views/messages/_form.html.erb
<% my_message_errors %>
			<div class = 'central_field' style = 'width: 90%;'>
				<%= form_for(@message) do |f| %>
					<%= hidden_field :return_to, :link, :value => @return_to %>
					<% if action_name != 'edit' %>
					<%= f.hidden_field :message_id, :value => params[:message][:message_id] if params[:message][:message_id] != nil %>
					<%= f.hidden_field :photo_id, :value => params[:message][:photo_id] if params[:message][:photo_id] != nil %>
					<%= f.hidden_field :video_id, :value => params[:message][:video_id] if params[:message][:video_id] != nil %>
					<%= f.hidden_field :article_id, :value => params[:message][:article_id] if params[:message][:article_id] != nil %>
					<%= f.hidden_field :topic_id, :value => params[:message][:topic_id] if params[:message][:topic_id] != nil %>
					<%= f.hidden_field :theme_id, :value => params[:message][:theme_id] if params[:message][:theme_id] != nil %>
					<%= f.hidden_field :photo_album_id, :value => params[:message][:photo_album_id] %>
					<% end %>
				  <div class='field' <%= @content_f_color.html_safe %>>
					<%= @content_error.html_safe %>
					<%= f.label :content, 'Текст сообщения' %><br />
					<%= f.text_area :content, :cols => '76', :rows => '7', :onKeyUp => 'changingTextarea(this)', :defaultRows => '7'%>
				  </div>
					<table>
						<tr>
							<td style = 'width: 450px; height: 100px;'>	
								<%= to_uploader_photos.html_safe %>
							</td>
							<td>
							  <div class = 'field'>
								<%= f.label :attachment_files, 'Вложения: ' %> 
								<%= f.file_field :attachment_files, :multiple => true %>
							  </div>
							</td>
						</tr>
					</table>

				  <div class='actions'>
					<%= f.submit @button_name %>
				  </div>
				<% end %>
			</div>
	  <div class = 'central_field'>
	  Смайлы
	  <hr />
		<%= smiles_draw %>
	  </div>

app/views/messages/edit.html.erb
<%= navigation_string.html_safe %>
<% my_message_errors %>
<br />
<div id = 'b_wrapper'>
		<div id = 'newMsgForm'>
			<%= newMessageFormInitial('block', '.edit_message').html_safe %>
		</div>
</div>
<br />  
<%= navigation_string.html_safe %>
<br />

app/views/messages/index.html.erb
<h1>Listing messages</h1>
<%= @messages.count.to_s %>
<table>
  <tr>
	<th>Id</th>
    <th>User</th>
    <th>Topic</th>
    <th>Theme</th>
    <th>Message</th>
    <th>Photo</th>
    <th>Video</th>
    <th>First message</th>
    <th>Updater</th>
    <th>Theme</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @messages.each do |message| %>
  <tr>
	<td valign = 'top'><%= message.content.length %></td>
    <td valign = 'top'><%= message.user_id %></td>
    <td valign = 'top'><%= message.topic_id %></td>
    <td valign = 'top'><%= message.theme_id %></td>
    <td valign = 'top'><%= message.message_id %></td>
    <td valign = 'top'><%= message.photo_id %></td>
    <td valign = 'top'><%= message.video_id %></td>
    <td valign = 'top'><%= message.first_message_id %></td>
    <td valign = 'top'><%= message.updater_id %></td>
    <td valign = 'top'><%= message.theme %></td>
    <td valign = 'top'><%= message.content %></td>
    <td><%= link_to 'Show', message %></td>
    <td><%= link_to 'Edit', edit_message_path(message) %></td>
    <td><%= link_to 'Destroy', message, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
   <tr>
    <td valign = 'top'>-</td>
    <td valign = 'top'>-</td>
    <td valign = 'top'>-</td>
    <td valign = 'top'>-</td>
    <td valign = 'top'>-</td>
    <td valign = 'top'>-</td>
    <td valign = 'top'>-</td>
    <td valign = 'top'>-</td>
    <td valign = 'top'>-</td>
    <td valign = 'top'>-</td>
    <td valign = 'top'>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
  </tr> 
<% end %>
</table>

<br />
<br />
<br />

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<%= navigation_string.html_safe %>
<% my_message_errors %>
<br /><br />
<div class = 'central_field' id = 'b_wrapper'>
	<% if @theme != nil %>
		<%= theme_show_block(false).html_safe %>
	<% end %>
	<% if @message_to != nil %>
			<%= message_theme_box(@message_to, false, 1).html_safe %>
	<% end %>
	<div id = 'newMsgForm'>
		<%= new_msg_frm %>
	</div> 
</div>
<br />
<%= navigation_string.html_safe %>
<br /><br />

app/views/messages/replace_message.html.erb
		<%= notice %>
		<%= form_for(:replace_message, :url => '/do_replace_message') do |f| %>
			<%= f.hidden_field :current_message, :value => @message.id %>
			<div class = 'field'>
				<%= f.label :topic_id, "Раздел:" %><br /> 
				<%= my_collection_select(@collection, "topic_id", "split_theme", @default, "") %> 
			</div>
			<div class = 'field'>
				<%= f.label :new_theme_id, "Целевая тема:" %><br /> 
				<%= my_collection_select(@themes_collection, "theme_id", "split_theme", {}, "Выберите тему из списка") %> <br />
			</div>			
			<div class = 'field'>
				<%= f.label :make_new_as_theme, "Вынести в отдельную тему" %><%= f.check_box :make_new_as_theme, :class => 'check_box' %><br />
			</div>
			<div class = 'field'>
				<%= f.label :theme_name, 'Название новой темы' %><br />
				<%= f.text_field :new_theme_name, :size => 70, :class => 't_field' %><br />
			</div>
			<br />
			<%= f.submit "Произвести изменение", :class => 'butt' %>
		<% end %>
		<div class = 'central_field' id = 'b_wrapper'>
		<h3>Целевая тема</h3>
		<div id = 'target_theme'>
		</div>
		<h3>Переносимое сообщение</h3>	
		<% i=0 %>
		<%= message_theme_box(@message, false, i).html_safe %>
			<% if @message.get_tread != [] %>
				<% @message.get_tread.each do |msg| %>
					<% i+=1 %>
					<%= message_theme_box(msg, false, i).html_safe %>
				<% end %>
			<% end %>
		</div>

app/views/messages/show.html.erb
<%= navigation_string.html_safe %>
<br />
<div class = 'central_field' id = 'b_wrapper'>
	<br />
	<p id="notice"><%= notice %></p>
	<div id = 'b_wrapper'>
		<% if @theme != nil %>
				<%= theme_show_block(false).html_safe %>
		<% end %>
		<% if @photo != nil %>
			#todo
		<% end %>
		<% if @video != nil %>
			<%= video_show_block.html_safe %>
		<% end %>
		<%= newMessageFormInitial('none', '#new_message').html_safe %>
		<% i=1 %>
		<%= message_theme_box(@message, true, i).html_safe %>
		<% if @messages != [] %>
			<% @messages.each do |message| %>
				<% i+=1 %>
				<%= message_theme_box(message, true, i).html_safe %>
			<% end %>
		<% else %>
			<p class = 'istring norm'>В теме нет ни одного сообщения...</p>
		<% end %>
	</div>  
</div>
<br />
<%= navigation_string.html_safe %>
<br />
<br />