config/routes.rb
VisotaParaclubRu::Application.routes.draw do

  resources :voices, :only => [:create, :destroy]	
  resources :votes
  resources :events

  post "events/upload_photos"
  match '/events/:id/upload_photos', :to => 'events#upload_photos' #загрузка с помощью dropzone.js и собственную функцию
	get "admin_tools/deleted_albums"   #удалённые альбомы
	get "admin_tools/deleted_themes"   #удалённые темы
	get "admin_tools/deleted_messages" #удалённые сообщения или комментарии
	get "admin_tools/deleted_articles" #удалённые статьи
	get "admin_tools/deleted_photos"   #удалённые статьи
	get "admin_tools/hidden_albums"    #скрытые альбомы
	get "admin_tools/hidden_themes"	   #скрытые альбомы
	get "admin_tools/hidden_messages"  #скрытые сообщения
	get "admin_tools/hidden_articles"  #скрытые статьи
	get "admin_tools/hidden_photos"    #скрытые фотографии
	get "admin_tools/deleted_entities" #удалённые объекты
  get "admin_tools/hidden_entities"  #скрытые объекты	
	get "admin_tools/site_images" #изображения для сайта	
	get "admin_tools/entities_recovery"	#Восстановление удалённых объектов
	get "admin_tools/disabled_events" #Скрытые новости
	get "admin_tools/adaptation_to_new"     #Создать темы
  
  resources :articles
  get "articles/bind_videos_and_albums"
  post "articles/upload_photos"
  match '/articles/:id/upload_photos', :to => 'articles#upload_photos'
  match '/articles/:id/bind_videos_and_albums', :to => 'articles#bind_videos_and_albums'

  resources :old_messages, :only => [:index, :edit, :update, :destroy]
  get "old_messages/get_old_messages"
  get "old_messages/old_msg_users"
  get "old_messages/assign_users_to_old_msgs"
  post "old_messages/assign_users_to_old_msgs"
  
  resources :messages
  get "messages/replace_message"
  get "messages/do_replace_message"
  post "messages/upload_photos"
  match '/messages/:id/replace_message', :to => 'messages#replace_message'
  match '/messages/:id/upload_photos', :to => 'messages#upload_photos' #загрузка с помощью dropzone.js и собственную функцию photosUploader() в application.js
  match '/do_replace_message', :to => 'messages#do_replace_message'
  
  resources :themes
  get "themes/merge_themes"
  get "themes/get_themes_list"
  post "themes/do_merge_themes"
  post "themes/theme_switcher"
  post "themes/add_photos"
  post "themes/add_files"
  post "themes/upload_photos"
  match '/themes/:id/theme_switcher', :to => 'themes#theme_switcher'
  match '/get_themes_list', :to => 'themes#get_themes_list'
  match '/themes/:id/merge_themes', :to => 'themes#merge_themes'
  match '/themes/:id/new_message', :to => 'themes#new_message' #Новое сообщение в теме
  match '/themes/:id/add_photos', :to => 'themes#add_photos' #Загрузка фото
  match '/themes/:id/add_files', :to => 'themes#add_files' #Загрузка файлов
  match '/do_merge_themes', :to => 'themes#do_merge_themes'
  match '/themes/:id/upload_photos', :to => 'themes#upload_photos' #загрузка с помощью dropzone.js и собственную функцию photosUploader() в application.js

  resources :topics
  match '/visota_life', :to => 'topics#index'
  match '/gost.htm', :to => 'topics#index'

  resources :videos
  get "videos/new_comment"
  match '/videos/:id/new_comment', :to => 'videos#new_comment'

  resources :photos
  get "photos/edit_photos"
  get "photos/recovery"
  post "photos/edit_photos"
  post "photos/update_photos"
  match '/photos/:id/recovery', :to => 'photos#recovery' #восстановление
  match '/edit_photos', :to => 'photos#edit_photos'
  match '/update_photos', :to => 'photos#update_photos'

  resources :photo_albums
  get "photo_albums/unbinded_to_article_albums"
  post "photo_albums/upload_photos"
  get "photo_albums/get_albums_list"
  match '/get_albums_list', :to => 'photo_albums#get_albums_list'
  match '/unbinded_to_article_albums', :to => 'photo_albums#unbinded_to_article_albums'#Ссылка на вывод списка альбомов не прикрепленных к статье...
  match '/photo_albums/:id/upload_photos', :to => 'photo_albums#upload_photos' #загрузка с помощью dropzone.js и собственную функцию photosUploader() в application.js

  resources :steps
  
  resources :users
  get "users/password_mail_sent"
  get "users/make_mail"
  get "users/remember_password"
  get "users/mail_switcher"
  get "users/thanks"
  put "users/update_mailer"
  get "users/user_check"
  get "users/mail_test"
  get "users/check_email_and_name"
  get "users/videos"
  get "users/photo_albums"
  get "users/articles"
  get "users/steps"
  match '/password_mail_sent', :to => 'users#password_mail_sent'
  match '/make_mail', :to => 'users#make_mail'
  match '/remember_password', :to => 'users#remember_password'
  match '/thanks', :to => 'users#thanks'
  match '/mail_switcher', :to => 'users#mail_switcher'
  match '/user_check', :to => 'users#user_check'
  match "/pilots", :to => 'users#index'
  match "/welcome", :to => 'users#welcome'
  match "/update_mailer", :to => 'users#update_mailer'
  match "/check_email_and_name", :to => 'users#check_email_and_name' #проверка имени и почтового адреса на занятость.
  match "/users/:id/videos", :to => "users#videos"
  match "/users/:id/steps", :to => "users#steps"
  match '/users/:id/photo_albums', :to => 'users#photo_albums'
  match '/users/:id/articles', :to => 'users#articles'
  
  resources :sessions, :only => [:new, :create, :destroy]
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  match '/create_session',  :to => 'sessions#create'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  
  get "pages/index"
  get "pages/school"
  get "pages/contacts"
  get "pages/about_us"
  get "pages/feed"
  get "pages/search"
  match '/index', :to => 'pages#index'
  match '/school', :to => 'pages#school'
  match '/about_us', :to => 'pages#about_us'
  match '/contacts', :to => 'pages#contacts'
  match '/styles', :to => 'pages#styles'
  match '/feed', :to => 'pages#feed'
  match '/search', :to => 'pages#search'
  

  root :to => 'pages#index'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :description, :image, :name, :image_cache
  has_many :messages
  has_many :themes
  #has_many :old_messages
  mount_uploader :image, ImageUploader
  
  def alter_image
   return '/files/undefined.png' if image == nil or image == ''
   return image if image != nil and image != ''
  end
  
  def last_active_themes(is_not_authorized)
	v_status = 1
	v_status = [1,2] if !is_not_authorized
    return self.themes.select('id, name, last_message_date, user_id, created_at').where(:status_id => [1,3], :visibility_status_id => v_status).order('last_message_date DESC').limit(4)
  end
  
  def entities_count(is_not_authorized)
	c = {:cThemes => 0, :cMessages => 0}
	v_status = 1
	v_status = [1,2] if !is_not_authorized
	c[:cThemes] = self.themes.where(:status_id => [1,3], :visibility_status_id => v_status).count
	c[:cMessages] = self.messages.where(:status_id => 1, :visibility_status_id => v_status).count
	return c
  end
  
  #Для адаптации старого форума в новый
  def firstMessages
	self.messages.where(:photo_id => nil, :video_id => nil, :first_message_id => nil).order('id ASC')
  end
 
  def firstMessagesWithoutName #Находим все первые сообщения без заголовка
	msgs = []
	frst_messages = []
	msgs += self.messages.select(:id).where(:photo_id => nil, :video_id => nil, :first_message_id => nil, :name => nil)
	msgs += self.messages.select(:id).where(:photo_id => nil, :video_id => nil, :first_message_id => nil, :name => '')
	if msgs != []
		frst_messages = Message.find_all_by_id(msgs, :order => 'id ASC')
	end
	return frst_messages 
  end
  def firstMessagesWithName #Находим все первые сообщения c заголовком
	self.firstMessages - self.firstMessagesWithoutName 
  end
  
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
include ThemesHelper
include EventsHelper
  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
	@title = "Клубная Жизнь"
    respond_to do |format|
	  format.html# index.html.erb
      format.json { render :json => @topics }
    end
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @topic = Topic.find(params[:id])
	@title = @topic.name
	@themes_per_page = 25
	if is_not_authorized?
		@themes = @topic.themes.where('status_id in (1, 4) and visibility_status_id = 1').paginate(:page => params[:page], :per_page => @themes_per_page, :order => 'last_message_date DESC')
	else
		@themes = @topic.themes.where('status_id in (1, 4)and visibility_status_id in (1,2)').paginate(:page => params[:page], :per_page => @themes_per_page, :order => 'last_message_date DESC')
	end
	@path_array = [
					{:name => 'Клубная жизнь', :link => '/visota_life'},
					{:name => @topic.name, :link => topic_path(@topic)}
				  ]
    respond_to do |format|
      format.html# show.html.erb
      format.json { render :json => @topic }
    end
  end

  # GET /topics/new
  # GET /topics/new.json
  def new
	if user_type == 'super_admin'
		@topic = Topic.new
		respond_to do |format|
		  format.html# new.html.erb
		  format.json { render :json => @topic }
		end
	else
		redirect_to '/404'
	end
  end

  # GET /topics/1/edit
  def edit
	if user_type == 'super_admin'
		@topic = Topic.find(params[:id])
		@title = "Изменение раздела '#{@topic.name}'"
		respond_to do |format|
		  format.html# new.html.erb
		  format.json { render :json => @topic }
		end
	else
		redirect_to '/404'
	end
  end

  # POST /topics
  # POST /topics.json
  def create
	if user_type == 'super_admin'
		@topic = Topic.new(params[:topic])

		respond_to do |format|
		  if @topic.save
			format.html { redirect_to @topic, :notice => 'Раздел успешно создан' }
			format.json { render :json => @topic, :status => :created, :location => @topic }
		  else
			format.html { render :action => "new"}
			format.json { render :json => @topic.errors, :status => :unprocessable_entity }
		  end
		end
	else
		redirect_to '/404'
	end
  end

  # PUT /topics/1
  # PUT /topics/1.json
  def update
	if user_type == 'super_admin'
		@topic = Topic.find(params[:id])

		respond_to do |format|
		  if @topic.update_attributes(params[:topic])
			format.html { redirect_to @topic, :notice => 'Раздел успешно обновлён' }
			format.json { head :no_content }
		  else
			format.html { render :action => "edit"}
			format.json { render :json => @topic.errors, :status => :unprocessable_entity }
		  end
		end
	else
		redirect_to '/404'
	end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
	if user_type == 'super_admin'
		@topic = Topic.find(params[:id])
		@topic.destroy

		respond_to do |format|
		  format.html { redirect_to topics_url }
		  format.json { head :no_content }
		end
	else
		redirect_to '/404'
	end
  end
  
  
end

app/helpers/topics_helper.rb
module TopicsHelper
	
	def index_topic_buttons(topic)
		[
		 {:name => 'Перейти в раздел', :access => true, :link => "#{topic_path(topic)}", :type => 'follow', :id => 'showTopic' },
		 {:name => "Добавить тему в раздел \"#{topic.name}\"", :access => userCreateThemeInTopic?(topic), :type => 'add', :link => "#{new_theme_path(:t => topic.id)}", :id => 'newTheme'}, 
		 {:name => 'Редактировать', :access => is_super_admin?, :type => 'edit', :link => "#{edit_topic_path(topic)}", :id => 'editTopic'}
		]
	end
	def top_index_topic_buttons
		"#{control_buttons([{:name => "Опросы", :access => true, :type => 'follow', :link => votes_path}, {:name => 'Новый раздел', :access => is_super_admin?, :type => 'add', :link => "#{new_topic_path}", :id => 'newTopic'}])}"
	end
	def show_topic_buttons(topic)
		[
		 {:name => "Добавить тему", :access => userCreateThemeInTopic?(topic), :type => 'add', :link => "#{new_theme_path(:t => topic.id)}", :id => 'newTheme'}, 
		]
	end
	def visota_life_panel

		v = {:name => "Опросы", :access => true, :type => 'grey', :link => votes_path}
	#	m = {:name => "Архив сообщений с para.saminfo.ru", :access => true, :type => 'grey', :link => old_messages_path}
	#	m[:selected] = true if controller.controller_name == 'old_messages'
		b = [v]
		return b
	end
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, 'Название раздела' %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image, 'Тематическое изображение раздела' %><br />
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :description, 'Описание раздела' %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit 'Сохранить' %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<%= render 'form' %>

<%= link_to 'Перейти к разделу', @topic, :class => 'b_link' %> |
<%= link_to 'Перуйти к списку разделов', topics_path, :class => 'b_link' %>

app/views/topics/index.html.erb
<div class = 'c_box'>
    <div class = 'central_field' style = 'width: 90%; z-index: 15;'>
        <%= top_index_topic_buttons.html_safe %>
    </div>
</div>
<% @topics.each do |topic| %>
	<div class = 'c_box'>
				<div class = 'central_field' style = 'width: 90%; z-index: 15;'>
					</br>
						<div class = 'central_field' style = 'width: 100%;'>
							<%= link_to(topic.name, topic, :class => 'b_link_bold', :style => 'font-size: 14pt;') %>	
						</div>
					</br>
					<% 
						themes = topic.last_active_themes(is_not_authorized?)
						if themes != [] 
					%>
						<table class = 'v_table' id = 'themes_list_vl'>
							<tr>
								<th id = 'first'>Тема</th>
								<th>Автор крайнего сообщения</th>
								<th>Дата</th>
							</tr>
							<% themes.each do |theme| %>
								<tbody class = 't_link' link_to = '<%= theme_path(theme)%>'>
								<tr>
									<td class = 't_name' id = 'first'>
										<%= theme.name %>
									</td>
									<% 
										msg = theme.last_message
										if msg != nil
									%>
											<td class = 'usr'>
												<%= msg.user.name  %>
											</td>
											<td class = 'date'>
												<%= my_time(msg.created_at) %>
											</td>
									<% else %>																		
											<td class = 'usr'>
												<%= theme.user.name %>
											</td>
											<td class = 'date'>
												<%= my_time(theme.created_at) %>
											</td>
									<% end %>	
									
								</tr>
								</tbody>
							<% end %>
							
						</table>
						<br />
						<div class = 'central_field' style = 'width: 100%;'>
							<table style = 'width: 100%;'>
								<tr>
									<td align = 'left' valign = 'middle'>
										<%= control_buttons(index_topic_buttons(topic)).html_safe %>
									</td>
									<td style = 'width: 200px;'>
										<% entities_count = topic.entities_count(is_not_authorized?) %>
										<p class = 'istring_m norm medium-opacity'>Тем: <%= entities_count[:cThemes].to_s %> Сообщений: <%= entities_count[:cMessages].to_s %></p>
									</td>
								</tr>
							</table>
							<br />
						</div>
					<% else %>
						<p class = 'istring'>В данном разделе нет ни одной активной темы...</p>
					<% end %>
				</div>
	</div>
	<br />
<% end %>
<div class = 'c_box'>
	<div class = 'central_field' style = 'width: 90%; height: 150px;'>
			</br>
			<div class = 'central_field' style = 'width: 100%;'>
				<%= link_to('Архив сообщений с para.saminfo.ru', old_messages_path, :class => 'b_link_bold', :style => 'font-size: 14pt;') %>	
			</div>
			</br>
			<div class = 'central_field' style = 'width: 90%;'>
				<p class = 'istring_m medium-opacity'>Здесь размещены сообщения сохранённые с старого сайта, который располагался по адресу <a class = 'b_link_i' rel = 'nofollow' target ='_blank' href='http://para.saminfo.ru/'>para.saminfo.ru...</a></p>
			</div>
			<br /><br /><br />
			<div class = 'central_field' style = 'width: 100%;'>
				<table style = 'width: 100%;'>
					<tr>
						<td align = 'left' valign = 'middle'>
							<%= control_buttons([{:name=> 'Перейти в раздел', :type => 'follow', :link => old_messages_path, :access=>true}]).html_safe %>
						</td>
						<td style = 'width: 200px;'>
							<p class = 'istring_m norm medium-opacity'>Сообщений: <%= OldMessage.all.count.to_s %></p>
						</td>
					</tr>
				</table>
				
				<br />
			</div>
	</div>
	
	<br />
</div>
<br />
<br />
<br />

app/views/topics/new.html.erb
<h1>New topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<%= navigation_string.html_safe %>
<div class = 'central_field' id = 'w_1000'>
	<%= will_paginate @themes %>
</div>
<br/>
<div class = 'central_field' style = 'width: 90%;'>
	<h1><%= @topic.name %></h1>
	<br />
</div>
<%= "<div class = 'c_box'><div class = 'central_field' style = 'width: 91%;'>#{control_buttons(show_topic_buttons(@topic))}</div></div>".html_safe if control_buttons(show_topic_buttons(@topic)) != '' %>
<div class = 'c_box'>
	<div class = 'central_field' style = 'width: 90%;'>
	<%= themes_table.html_safe %>
	</div>
</div>
<div class = 'central_field' id = 'w_1000'>
	<%= will_paginate @themes %>
</div>
<br />

<%= navigation_string.html_safe %>
<br />
<br />
<br />